[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cnlp_llm"
version = "0.0.1"
description = "LLM training and evaluation for clinical NLP"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "inspect_ai~=0.3",
    "openai~=1.37",
    "click~=8.1",
    "trl~=0.9",
    "datasets~=2.20",
    "peft~=0.12",
]

[project.scripts]
"cnlp_llm" = "cnlp_llm.cli:main"

[project.urls]
Homepage = "https://github.com/Machine-Learning-for-Medical-Language/cnlp_llm"
Issues = "https://github.com/Machine-Learning-for-Medical-Language/cnlp_llm/issues"
