name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
      - ".github/workflows/**"
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Test with pytest
        run: |
          uv run -v --frozen --group test --python ${{ matrix.python-version }} pytest
