name: Lint, Format, and Typecheck

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "examples/**"
      - "pyproject.toml"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "examples/**"
      - "pyproject.toml"
      - ".github/workflows/**"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.11.0 # same as in pre-commit hooks and pyproject.toml
          args: check
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.11.0 # same as in pre-commit hooks and pyproject.toml
          args: format --check
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          files: "**/*.md"
          separator: ","
      - uses: DavidAnson/markdownlint-cli2-action@v19
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
