name: Build

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.7.1 # same as in pre-commit hooks and pyproject.toml
          args: check
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.7.1 # same as in pre-commit hooks and pyproject.toml
          args: format --check
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
